// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA0FT8RSDL2FDJj8yRKszTw7_o9Am-edk',
    appId: '1:304351299631:web:b94580f104e1abc8659eda',
    messagingSenderId: '304351299631',
    projectId: 'todo-b8aa6',
    authDomain: 'todo-b8aa6.firebaseapp.com',
    storageBucket: 'todo-b8aa6.appspot.com',
    measurementId: 'G-TMM5PHSVTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFpE4F8d4B46bzvZudSdJR-DiBO-d-iJo',
    appId: '1:304351299631:android:9a64a853d8a6bfd0659eda',
    messagingSenderId: '304351299631',
    projectId: 'todo-b8aa6',
    storageBucket: 'todo-b8aa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh2n8ZFKwupAIqKMDvOHQ57Robk9t0aAo',
    appId: '1:304351299631:ios:c67b761e4d7e4c49659eda',
    messagingSenderId: '304351299631',
    projectId: 'todo-b8aa6',
    storageBucket: 'todo-b8aa6.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh2n8ZFKwupAIqKMDvOHQ57Robk9t0aAo',
    appId: '1:304351299631:ios:c67b761e4d7e4c49659eda',
    messagingSenderId: '304351299631',
    projectId: 'todo-b8aa6',
    storageBucket: 'todo-b8aa6.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA0FT8RSDL2FDJj8yRKszTw7_o9Am-edk',
    appId: '1:304351299631:web:06d1ec5ffb6b23d1659eda',
    messagingSenderId: '304351299631',
    projectId: 'todo-b8aa6',
    authDomain: 'todo-b8aa6.firebaseapp.com',
    storageBucket: 'todo-b8aa6.appspot.com',
    measurementId: 'G-R46KFWQE0V',
  );

}